services:
  frontend:
    image: node:20-alpine
    container_name: react_frontend_ADES
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      VITE_PROXY_TARGET: http://nginx
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    depends_on:
      - nginx

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_app_ADES
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx_ADES
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: mysql_db_ADES
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  ml_models:
    build:
      context: ./ml_models
      dockerfile: Dockerfile
    container_name: ml_models_ADES
    working_dir: /app
    volumes:
      - ./ml_models:/app
    ports:
      - "8001:8001"
    command: uvicorn api.main:app --host 0.0.0.0 --port 8001 --reload

volumes:
  mysql_data:
